# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy angular app to Azure Web App - epprns

on:
  push:
    # branches:
    #   - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: List dist directory for debugging
        run: ls -al ./dist/

      - name: Zip artifact for deployment
        run: zip -r release.zip ./dist/*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: entry-track-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: entry-track-app

      - name: Unzip artifact for deployment
        run: |
          # Remove existing dist folder if it exists, but keep server.js and web.config
          if [ -d "./dist" ]; then
            echo "Removing existing dist folder..."
            rm -rf ./dist/*
            # You may want to move server.js and web.config to a temporary location before removing
            mv ./dist/server.js ./dist/server_temp.js || true
            mv ./dist/web.config ./dist/web_temp.config || true
            rm -rf ./dist
            # Restore server.js and web.config
            mv ./dist/server_temp.js ./dist/server.js || true
            mv ./dist/web_temp.config ./dist/web.config || true
          fi
          # Unzip the release.zip
          unzip release.zip

      - name: Delete zip file
        run: rm release.zip

      # - name: Login to Azure
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_03F73405CBA8473E93A3DFFCC4DC73AE }}
      #     tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8A8B7181E2274C5597D38CF188D747AB }}
      #     subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2B1B732C99C040BE9557E377CBD2A0E7 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'entry-track'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2688E238595D4AFD964099BED2FD83BE }}
          package: .